### ISSUE TITLE
Unexpected conversion of lodgement_date

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/atdisplanningalertsfeed#5]
### Observed behaviour

* https://jamezpolley.github.io/atdis_utcdatetime_test/atdis/1.0/applications.json has a sample ATDIS feed based on live data observed in an Authority's system. This Authority is in NSW, so their local timezone is AEST/AEDT (UTC+10/UTC+11).
* The single entry in the feed has `"lodgement_date": "2018-08-21T22:46:03Z"`. This corresponds with `2018-08-22T08:46:03+10:00` in the Authority's local time.
* The [ATDIS feed tester](https://www.planningalerts.org.au/atdis/test?url=https%3A%2F%2Fjamezpolley.github.io%2Fatdis_utcdatetime_test%2Fatdis%2F1.0%2Fapplications.json%3Flast_modified_date_end%3D%26last_modified_date_start%3D%26lodgement_date_end%3D%26lodgement_date_start%3D) confirms that this feed is valid.
* The feed tester presents the lodgement date as `lodgement_date | August 21, 2018 22:46 (9 months ago)`
* The scraper at https://github.com/jamezpolley/atdis_utcdatetime_test uses this gem to parse the feed. As can be seen on https://morph.io/jamezpolley/atdis_utcdatetime_test, it enters this data into the sqlite database as `2018-08-21`

### Expected behaviour

I can think of three outcomes that I would consider reasonable.

1) For the lodgement date to be presented exactly as provided in the feed, as `2018-08-21T22:46:03Z`.
2) For the lodgement date to be presented in the Authority's local time - `August 22, 2018 08:46` for the feed tester and `2018-08-22` in the scraper output.
3) For the lodgement date to be presented in my local time - `August 22, 2018 08:16`, if my local time happened to be Adelaide.

### Speculation

* I think that this feed conforms with the ATDIS spec.

  * Section 4.3.1 says:
    > Dates can be specified with or without time information. For example, the following are both valid date values (see also 4.3.8):
    > * `"determination_date": "2013-06-20T02:01:07Z"`
    > * `"determination_date": "2013-06-20"`

    This seems to give justification for dates being presented as a full date+time, in UTC.

    In addition, the sample data in section 6.4 contains `"lodgement_date": "2013-04-20T02:01:07Z"` - again, establishing precedent for presenting a date as a full date+time in UTC.

  * Section 4.3.8 says:
    > Any field within the schema of the form *_date or timestamp should be treated as an ISO-8601 date format. See: http://www.w3.org/TR/NOTE-datetime for details. 

    The dates specified seem to be valid ISO-8601 date formats.

  I think that there's probably a good case to be made for changing the spec; but the feed seems to conform to the current spec, and yet the dates as parsed aren't coming out the way I'd expect.
* I note that I can't see anywhere in the spec that would permit for a local timezone to be specified. 
  * In the specific case of PlanningAlerts, manually tracking the local timezone for each Authority doesn't seem like too much of a hassle: we already know which start the Authority is and each state in Australia only has a single timezone, so we probaly only need to map states to timezones.
  * Every other consumer would have to do something similar for every feed
* It may not always make sense to talk of "the Authority's" timezone.
  * As far as I'm aware, all the authorities that PlanningAlerts currently tracks only operate in one state, but if we had a federal body that would be different.
  * In the US, it's common to have more than one timezone within a state (https://simple.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_time_zone)
* I think that https://github.com/planningalerts-scrapers/atdisplanningalertsfeed/blob/b9719baec18ce57dc3c49265d3aafb34dbc97749/lib/atdisplanningalertsfeed.rb#L102 is the spot in this scraper which casts this to a date. I think this line is acting correctly based on the information it's been given - that is, it's returning the correct date in UTC.
    * Based on a cursory reading of the docs, I think that we'd need to do something like:
    ````ruby
    application.info.lodgement_date.in_time_zone('Australia/Sydney').to_date if application.info.lodgement_date
    ````
    * If we do this here, in the scraper, we've discarded most of the time and the timezone. Anyone using the data from the scraper will have the right date in the Authority's local time, but will have lost the time of day and won't be able to convert to the viewer's local time if that's needed. However, it means that consumers of the data from Morph don't need to worry about timezone math for these dates as there's nothing they could do with the dates, and it means that future date is identical to everything we've done in the past.
    * If we don't do it here, then I'd suggest that the scraper should leave the information unchanged. This would mean that the Consumer has the information they need to convert to a different timezone if needed. This would assume that the Consumer is aware of the relevant timezone for each feed.
    
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nmwt)

**Comment by jamezpolley** [comment]
I'm going to make two suggestions:

1) Long term, I think this should be noted as something to improve for any future version of the ATDIS spec
2) Short term, I think the simplest fix would be to modify `atdisplanningalertsfeed.rb` so that a timezone, if provided, is used when converting date/time fields to dates. If no timezone is provided, the current behaviour should be used.

**Comment by jamezpolley** [comment]
I think that in the short-term, (1) is the approach that is going to require the least change. (2) would allow for the data to be represented to the eventual viewer in their local timezone rather than the council timezone if that's desired; but I imagine it would always make more sense to be talking about the council's local timezone.

**Comment by mlandauer** [comment]
> If an ATDIS feed presents "lodgement_date":"2018-08-07", it will always be treated as a date and be presented as "2018-08-06" (in whatever regional format is used for dates)

@jamezpolley could you please explain this again using some different words. This makes no sense to me currently. What is being presented where? what's going in to where? and what's coming out where?

**Comment by mlandauer** [comment]
Perhaps if you reworded it very clearly as:

This what you need to do to reproduce the problem. This is what you put in. Then you see this in the ATDIS feed. Then you see this in the sqlite database when you put it through the scraper ...

Then explain why this is wrong.

Then explain what it should do instead.

Only then, do you explain what you think might be causing the problem. And what possible solutions there are.

In the way it's currently worded above it's all a bit jumbled up and I'm not sure what is observed and what is conjecture.

**Comment by mlandauer** [comment]
Thanks @jamezpolley for updating the wording. That's all much clearer now. Much easier to follow and understand.

**Comment by mlandauer** [comment]
Getting back to fixing this now

**Comment by mlandauer** [comment]
I've also updated all the scrapers that use this gem to use the latest version
